-- Disk usage doesn't change fast enough for min/avg/max per hour to add signal
-- — it drifts day-over-day, so the perf-alert threshold+breach model already
-- covers "disk got full", nothing to plot.
--
-- The historical disk columns are intentionally retained. Removing columns
-- from a live database is not an acceptable automatic migration because it
-- destroys historical data and makes rollback impossible.
--
-- Memory and CPU stay in the rollup — those spike and recover on human
-- timescales and the chart shape genuinely tells you something. New code may
-- stop reading the legacy columns, but migrations must leave their values.
